### ISSUE TITLE
Warnings displayed in example data-set

### ISSUE THREAD

**Issue by artistsm** [SMAPPNYU/mediascores#26]
The mediascores package when run on the example data-set gives the following warnings.

```
Warning messages:
1: The largest R-hat is 1.25, indicating chains have not mixed.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#r-hat 
2: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#bulk-ess 
3: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#tail-ess 
```

In the vignette, it is mentioned that R-hat is less than 1.1.  I get similar warnings on other custom data-sets that I have used. I think I have followed the instructions properly . Could you please help me fix/troubleshoot this issue.

**Comment by GregoryEady** [comment]
This might be due to changes that the Stan team has implemented in Stan recently. I will re-run the model on the packaged dataset and see if there is anything to worry about with those warnings.

**Comment by artistsm** [comment]
Thank you for the response. Will look forward to your answer.

**Comment by GregoryEady** [comment]
I have re-run the model on the packaged data, with chains = 4, cores = 4, warmup = 1000, iter = 2000.

I do not have any problem with the r-hat (perhaps because I set the warmup to 1000 instead of 750), but I do get warnings regarding the effective sample size. For this, though, you can just run the chains longer (it must be a new Stan warning). You should be okay with iter = 6000. My guess, however, is that getting a higher effective sample size won't meaningfully change the estimates.
